module.exports = {
  GET_TEQUILA: 'GET_TEQUILA',
  GET_TEQUILA_RESPONSE: 'GET_TEQUILA_RESPONSE',
  GET_FABRICANTE: 'GET_FABRICANTE',
  GET_FABRICANTE_RESPONSE: 'GET_FABRICANTE_RESPONSE',
  GET_USUARIO: 'GET_USUARIO',
  GET_USUARIO_RESPONSE: 'GET_USUARIO_RESPONSE',
};
