apiVersion: v1
kind: Service
metadata:
  name: kubebsg
  labels:
    app: kubebsg
spec:
  selector:
    app: kubebsg
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
