---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: graphql-svc
  name: graphql-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: graphql-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: graphql-svc
    spec:
      containers:
      - image: graphql_svc:v6
        imagePullPolicy: Never
        name: graphql-svc
        env:
          - name: TEQUILA_SVC_URI
            value: http://tequila-svc.default.svc.cluster.local
          - name: PRODUCER_SVC_URI
            value: http://producer-svc.default.svc.cluster.local
          - name: USER_SVC_URI
            value: http://user-svc.default.svc.cluster.local
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: graphql-svc
  name: graphql-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  graphql-svc_mapping
      prefix: /api/
      rewrite: /
      service: graphql-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: graphql-svc
  sessionAffinity: None
  type: ClusterIP
