---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: tequila-svc
  name: tequila-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tequila-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tequila-svc
    spec:
      containers:
      - image: tequila_svc:v4
        imagePullPolicy: Never
        name: tequila-svc
        env:
          - name: PERSISTENCY_SVC_URI
            value: http://persistency-svc.default.svc.cluster.local
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: tequila-svc
  name: tequila-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: tequila-svc
  sessionAffinity: None
  type: ClusterIP
